language:
    - python
python:
    - "3.6.2"
install:
    - pip install -r requirements.txt
before_script:
    - python manage.py migrate
    - python manage.py collecstatic --no-input
    - echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', '', 'asdasdasd') if (User.objects.filter(username='admin').exists() == False) else None" | python manage.py shell
script:
    - python manage.py test
