# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20171111_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='nombre')),
                ('internal_name', models.CharField(blank=True, max_length=50, verbose_name='nombre interno')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name_plural': 'Etiquetas',
                'verbose_name': 'Etiqueta',
            },
        ),
    ]
