# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_resource_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='nombre')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name_plural': 'Tipos',
                'verbose_name': 'Tipo',
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='internal_name',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='nombre interno'),
        ),
    ]
