# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20171112_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='resources.Type', verbose_name='Tipo'),
        ),
    ]
