# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='año')),
                ('section', models.IntegerField(verbose_name='año')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='nombre')),
                ('number', models.IntegerField(verbose_name='numero')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester', to='resources.Semester', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Semana',
                'verbose_name_plural': 'Semanas',
            },
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type', to='resources.Type', verbose_name='Tipo'),
        ),
    ]
