# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20171112_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='weeks',
            field=models.ManyToManyField(blank=True, related_name='weeks', to='resources.Week', verbose_name='Semanas'),
        ),
        migrations.AlterField(
            model_name='week',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester', to='resources.Semester', verbose_name='Semestre'),
        ),
    ]
