# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-13 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20171112_1901'),
        ('resources', '0009_auto_20171112_1950'),
    ]

    operations = [
    ]
