# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_merge_20171112_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
    ]
