# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_resource_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='generic_url',
            field=models.TextField(blank=True, verbose_name='url genérica'),
        ),
    ]
