# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_resource_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='section',
            field=models.IntegerField(verbose_name='section'),
        ),
    ]
