# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 04:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_remove_tag_internal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 4, 50, 57, 496606, tzinfo=utc), verbose_name='Fecha de publicación'),
            preserve_default=False,
        ),
    ]
