# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_resource_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
    ]
