# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 05:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_auto_20171118_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 5, 33, 42, 596652, tzinfo=utc), verbose_name='Fecha de termino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='week',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2017, 11, 18, 5, 33, 55, 512919, tzinfo=utc), verbose_name='Fecha de inicio'),
            preserve_default=False,
        ),
    ]
