# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0016_remove_resource_generic_url'),
        ('resources', '0020_semester_chat_id'),
    ]

    operations = [
    ]
